"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['AestheticSelector.py']
DATA_FILES = ['Model_weights.h5',
              'Model_definition.pkl',
              'instructions.png']
OPTIONS = {'packages':['PIL','wx','tensorflow','h5py','tf_keras_vis','matplotlib']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
