"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['AestheticSelector.py']
DATA_FILES = ['Keras_FinetuningAVA_inception_binaryWeights_mse_Adam_LR1e-05_BS64_E20_bestmodel0.h5',
              'Keras_FinetuningAVA_inception_binaryWeights_mse_Adam_LR1e-05_BS64_E20_model.pkl']
OPTIONS = {'packages':['PIL','wx','pandas','tensorflow','h5py']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
